image: python:latest

stages: 
    - build
    - test
    - integration
    
cache:
  paths:
    - ~/.cache/pip/

before_script:
  - python -V 
  - pip install -r requirements.txt

build:
    stage: build
    script:
        - python manage.py makemigrations poll
        - python manage.py makemigrations meetings
        - python manage.py migrate

test:
    stage: test
    script:
        - python manage.py test poll.tests_unit_test
        
integration:
    stage: integration
    script:
        - python manage.py test poll.tests_integration_test