# Generated by Django 2.2.7 on 2019-12-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_meeting_creation_time', models.IntegerField(verbose_name='sum_time')),
                ('num_created_meetings', models.IntegerField(default=0)),
                ('num_cancelled_or_modified_meetings', models.IntegerField(default=0)),
                ('num_reserved_rooms', models.IntegerField(default=0)),
            ],
        ),
    ]
