# Generated by Django 2.2.7 on 2019-12-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='sum_meeting_creation_time',
            field=models.IntegerField(default=0),
        ),
    ]
