# Generated by Django 2.2.7 on 2019-12-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20191214_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='average_response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='report',
            name='throughput',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='report',
            name='sum_meeting_creation_time',
            field=models.FloatField(default=0),
        ),
    ]
