# Generated by Django 2.2.7 on 2019-12-27 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20191227_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='req_count',
            field=models.IntegerField(default=0),
        ),
    ]
