# Generated by Django 3.0 on 2020-01-09 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to_poll_creator', models.BooleanField(default=True)),
                ('poll_email_to_participants', models.BooleanField(default=True)),
                ('mention_notification', models.BooleanField(default=True)),
                ('poll_close_notification', models.BooleanField(default=True)),
                ('meeting_creator_notification', models.BooleanField(default=True)),
                ('meeting_invitation', models.BooleanField(default=True)),
                ('cancel_meeting_notification', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notification_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
