# Generated by Django 2.2.7 on 2019-12-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
