# Generated by Django 2.2.7 on 2019-12-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_roomsreserved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomsReserved',
        ),
    ]
