# Generated by Django 3.0 on 2019-12-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_auto_20191222_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
    ]
