# Generated by Django 3.0 on 2019-12-25 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0009_participant_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='username',
        ),
    ]
