# Generated by Django 3.0 on 2019-12-25 15:40

import django.contrib.auth.validators
from django.db import migrations, models
import meetings.models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0010_remove_participant_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='participant',
            managers=[
                ('objects', meetings.models.ParticipantManager()),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='username',
            field=models.CharField(default=None, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
            preserve_default=False,
        ),
    ]
