# Generated by Django 3.0 on 2019-12-25 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0011_auto_20191225_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='username',
        ),
    ]
