# Generated by Django 2.2.7 on 2019-12-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0012_remove_participant_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='meeting_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
