# Generated by Django 3.0 on 2020-01-09 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created time')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='poll.Comment')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingPoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('closed', models.BooleanField(default=False)),
                ('hasDeadline', models.BooleanField(default=False)),
                ('deadline', models.DateTimeField(default=None, null=True, verbose_name='Close time')),
            ],
        ),
        migrations.CreateModel(
            name='PollTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start time')),
                ('end_date_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End time')),
            ],
        ),
        migrations.CreateModel(
            name='PollChoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agrees', models.IntegerField(choices=[(1, 'AGREE'), (3, 'AGREE_IFNEEDED'), (2, 'DISAGREE')])),
                ('chosen_time', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.PollTime')),
                ('poll', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='poll.MeetingPoll')),
                ('voter', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='meetingpoll',
            name='choices',
            field=models.ManyToManyField(default=None, to='poll.PollTime'),
        ),
        migrations.AddField(
            model_name='meetingpoll',
            name='comments',
            field=models.ManyToManyField(default=None, related_name='comments', to='poll.Comment'),
        ),
        migrations.AddField(
            model_name='meetingpoll',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meetingpoll',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
