# Generated by Django 3.0 on 2020-01-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoiceitem',
            name='agrees',
            field=models.IntegerField(choices=[(2, 'DISAGREE'), (3, 'AGREE_IFNEEDED'), (1, 'AGREE')]),
        ),
    ]
