# Generated by Django 2.2.7 on 2020-01-08 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoll',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Close time'),
        ),
    ]
