# Generated by Django 2.2.7 on 2019-11-29 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoll',
            name='creator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='meetings.Participant'),
            preserve_default=False,
        ),
    ]
