# Generated by Django 3.0 on 2019-12-12 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_auto_20191212_1229'),
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoll',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='participants', to='meetings.Participant'),
        ),
        migrations.AlterField(
            model_name='meetingpoll',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='meetings.Participant'),
        ),
    ]
