# Generated by Django 2.2.7 on 2020-01-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_meetingpoll_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpoll',
            name='deadline',
            field=models.DateTimeField(default=None, null=True, verbose_name='Close time'),
        ),
    ]
