# Generated by Django 3.0 on 2020-01-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_auto_20200108_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoiceitem',
            name='agrees',
            field=models.IntegerField(choices=[(2, 'DISAGREE'), (1, 'AGREE'), (3, 'AGREE_IFNEEDED')], default=2),
        ),
    ]
