# Generated by Django 2.2.7 on 2020-01-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200108_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingpoll',
            name='hasDeadline',
            field=models.BooleanField(default=False),
        ),
    ]
