# Generated by Django 2.2.7 on 2019-12-27 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created time'),
        ),
    ]
