# Generated by Django 3.0 on 2020-01-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_auto_20200109_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoiceitem',
            name='agrees',
            field=models.IntegerField(choices=[(2, 'DISAGREE'), (1, 'AGREE'), (3, 'AGREE_IFNEEDED')]),
        ),
    ]
