# Generated by Django 3.0 on 2020-01-08 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0004_meetingpoll_hasdeadline'),
        ('poll', '0004_auto_20200108_1647'),
    ]

    operations = [
    ]
