# Generated by Django 3.0 on 2020-01-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='poll',
        ),
        migrations.AddField(
            model_name='comment',
            name='replies',
            field=models.ManyToManyField(default=None, related_name='_comment_replies_+', to='poll.Comment'),
        ),
        migrations.AddField(
            model_name='meetingpoll',
            name='comments',
            field=models.ManyToManyField(to='poll.Comment'),
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
