# Generated by Django 3.0 on 2020-01-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20200108_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingpoll',
            name='comments',
            field=models.ManyToManyField(default=None, related_name='comments', to='poll.Comment'),
        ),
    ]
