# Generated by Django 3.0 on 2020-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_auto_20200109_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollchoiceitem',
            name='agrees',
            field=models.IntegerField(choices=[(1, 'AGREE'), (2, 'DISAGREE'), (3, 'AGREE_IFNEEDED')]),
        ),
    ]
