# Generated by Django 3.0 on 2020-01-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0007_auto_20200111_1139'),
        ('poll', '0005_auto_20200111_1153'),
    ]

    operations = [
    ]
