# Generated by Django 3.0 on 2020-01-08 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0008_auto_20200108_0836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
